UI/Controllers/HatController.cs
using AutoMapper;
using Business.Interface;
using Dto;
using Entity.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace UI.Controllers
{
    public class HatController : Controller
    {
        private readonly IElasticsearchService _elasticsearchService;
        private readonly IHatService _hatService;
        private readonly IHatKullanimService _hatKullanimService;
        private readonly IMapper _mapper;

        public HatController(IElasticsearchService elasticsearchService, IHatService hatService,IMapper mapper, IHatKullanimService hatKullanimService)
        {
            _elasticsearchService = elasticsearchService;
            _hatService = hatService;
            _mapper = mapper;
            _hatKullanimService = hatKullanimService;
        }
        [Authorize(Roles = "Admin,Editor")]
        public async Task<IActionResult> Index()
        {
           var hats = await _elasticsearchService.GetAllHatsFromElasticsearchAsync();
            var hatListeDtos = new List<HatListeDto>();

            foreach (var hat in hats)
            {
                var hatListeDto = new HatListeDto
                {
                    HatId = hat.HatId,
                    TelefonNo = hat.TelefonNo,
                    SatisDurumu = hat.SatisDurumu,
                    Ad = hat.Ad,
                    Soyad = hat.Soyad,
                    HatAcilisTarihi = hat.HatAcilisTarihi
                };

                hatListeDtos.Add(hatListeDto);
            }
            return View(hatListeDtos);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult HatSil(int id)
        {
            _hatService.Sil(new Hat { HatId = id });
            return Json(null);
        }
        [Authorize(Roles = "Admin,Editor")]
        public IActionResult HatKullanimDetay(int HatId)
        {
            return View(_mapper.Map<List<HatKullanimListeDto>>(_hatKullanimService.KullanimDetayListe(HatId)));

        }
    }
}

UI/Views/Hat/HatKullanimDetay.cshtml
@model List<HatKullanimListeDto>
@{
    ViewData["Title"] = "HatKullanimDetay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card mt-3" style="border-radius:10px">
    <h5 class="card-header"> Hat Kullanım Listesi</h5>
    <div class="card-body w-100">
        <table class=" table table-sm table-hover table border w-100">
            <tr>
                <th>Konuşma Tarihi</th>
                <th>Süre(dk)</th>
                <th>Tutar(₺)</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.KonusmaTarihi</td>
                    <td>@item.KonusmaSuresi</td>
                    <td>@item.Tutar ₺</td>
                </tr>
            }
        </table>
    </div>
</div>

UI/Views/Hat/Index.cshtml
@using System.Security.Claims;
@model List<HatListeDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card mt-3" style="border-radius:10px">
    <h5 class="card-header">Satışı Gerçekleşen Hat Listesi</h5>
    <div class="card-body w-100">
        <table class=" table table-sm table-hover table border w-100">
            <tr>
                <th>Ad</th>
                <th>Soyad</th>
                <th>Telefon Numarası</th>
                <th>Açılış Tarihi</th>
                <th>İşlemler</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Ad</td>
                    <td>@item.Soyad</td>
                    <td>@item.TelefonNo</td>
                    <td>@item.HatAcilisTarihi</td>
                    <td class="text-center">  <a asp-action="HatKullanimDetay" asp-controller="Hat" asp-route-HatId="@item.HatId" class="btn btn-success btn-sm duzenleButton"><i class="fas fa-edit"></i>Detay</a>
                        @if (User.HasClaim(x => x.Type == ClaimTypes.Role && x.Value == "Admin"))
                        {
                            <button class="silButonu btn btn-danger duzenleButton" data-id="@item.HatId">Sil</button>
                     }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<div id="silmeOnayPopup" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Silme Onayı</h4>
            </div>
            <div class="modal-body">
                <p>Silmek istediğinize emin misiniz?</p>
            </div>
            <div class="modal-footer">
                <button id="silOnayBtn" class="btn btn-danger">Evet, Sil</button>
                <button id="silmeIptalBtn" class="btn btn-succeces" data-dismiss="modal">İptal</button>
            </div>
        </div>
    </div>
</div>
@section JavaScript
    {
    <script>
        $(document).ready(function () {
            $(".silButonu").click(function () {
                var id = $(this).data("id");
                $("#silmeOnayPopup").modal("show");

                $("#silOnayBtn").click(function () {
                    $.ajax({
                        url: "/Hat/HatSil",
                        type: "POST",
                        data: { id: id },
                        success: function (result) {
                            alert("Silme işlemi başarıyla tamamlandı!");
                            location.reload();
                        },
                        error: function (xhr, status, error) {
                            alert("Silme işlemi sırasında bir hata oluştu.");
                        }
                    });

                    $("#silmeOnayPopup").modal("hide");
                });
            });
            $("#silmeIptalBtn").click(function () {
                $("#silmeOnayPopup").modal("hide");
            });
        });
    </script>
  
}